name: Lab4_CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pytest pytest-mock boto3 behave pylint

      - name: Run Unit Tests
        run: pytest tests/test_unit.py

      - name: Run BDD Tests
        run: behave

      - name: Start LocalStack & Integration Tests
        run: |
          docker-compose up -d
          sleep 15
          pytest tests/test_integration.py
